[package]
name = "kernel"
version = "0.1.33"
build = "build.rs"

[lib]
name = "kernel"
path = "src/lib.rs"
crate-type = ["staticlib"]

[dependencies]
bitflags = "1.0.3"
clippy = { version = "0.0.209", optional = true }
linked_list_allocator = "0.6.2"
raw-cpuid = "4.0.0"
redox_syscall = { path = "syscall" }
slab_allocator = { path = "slab_allocator", optional = true }
spin = "0.4.9"
serde_derive = "1.0"
serde-json-core = "0.0.1"
hashmap_core = "0.1.9"
sos = { path = "../sos-rs" }

[dependencies.goblin]
version = "0.0.15"
default-features = false
features = ["elf32", "elf64", "endian_fd"]

[dependencies.serde]
version = "1.0.76"
default-features = false
features = ["alloc"]

[dependencies.x86]
version = "0.9.0"
default-features = false

[dependencies.lazy_static]
version = "1.1.0"
features = ["spin_no_std"]

[features]
default = []
acpi = []
doc = []
graphical_debug = []
live = []
multi_core = []
pti = []
slab = ["slab_allocator"]
